### ISSUE TITLE
Removing on-the-fly generation of the Beam job `setup.py`

### ISSUE THREAD

**Issue by beczkowb** [allegro/bigflow#158]
Currently, we have util that generates `setup.py` on-the-fly for a beam job execution. The generated `setup.py` is not the same as the `project_setup.py` which causes various problems (f.e. not being able to reach resources from a beam job).

I suggest that we add project .whl to the resources (during build) so a beam process can just install ready to use the package instead of generating it using the generated `setup.py`.

**Comment by anjensan** [comment]
AFAIK 'beam' requires to have a 'setup.py' and tries to build python tarball himself, so it might be tricky to install whl.
https://github.com/apache/beam/blob/ad0c7f6a7c65199c6fc1d55f25dc976f73bbbec7/sdks/python/apache_beam/runners/portability/stager.py#L572

Instead we might consider switching to 'sdist':
 - Rename our 'project_setup.py' into 'setup.py'
 - [Optionally] We can refine API of 'bigflow.build' during this step, eg rename `bigflow.build.default_project_setup` to `bigflow.setup`;
 - Add `pyproject.toml` with `bigflow` dependency (as bigflow is imported from new `setup.py`)
 - Change `Dockerfile` - use `ADD dist/project_name_xx.tar.gz` instead of `RUN pip install ...`

Benefits: same 'setup.py' is used to build project & run it on beam.
Additional resources might be added with `setup(package_data=...)`.
